### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [anna-gladzinska/node-watermark#1]
- [x] bloku `try ... catch` użyj w funkcjach `addTextWatermarkToImage` i `addImageWatermarkToImage`, bo tam nie wyłapujemy żadnych błędów. Możesz sprawdzić, co się stanie jak popsujesz coś wewnątrz nich np. przy wywołaniu podasz błędną ścieżkę `addTextWatermarkToImage('./imgggg/' + ...`.
(Również do tych funkcji przenieś info o sukcesie i ponowne odpalanie appki)
- [x] wtedy `try ... catch` w `startApp` nie jest nam potrzebny, dubluje to, co robi `if ... else`, a `throw` zamień na `console.log`
(oczywiście zamysł z throw i catch jak najbardziej ma sens ale nie przy naszych założeniach :) )

**Comment by anna-gladzinska** [comment]
Ah nie w tym miejscu dałam, poprawione :)
